// AIRecommendationsCard.jsx
import React from 'react';
import './AIRecommendationsCard.css';

function AIRecommendationsCard() {
  // These recommendations would ideally be generated by an AI system based on user data
  const debtRecommendations = [
    "Consider consolidating high-interest debts to lower your monthly payments",
    "Focus on paying off the credit card with the highest interest rate first",
    "Set up automatic payments to avoid late fees and penalties",
    "Look into refinancing options for your student loans"
  ];
  
  const spendingRecommendations = [
    "Your housing costs are above 30% of your income, consider finding a roommate",
    "Reduce dining out expenses by cooking more meals at home",
    "Look for cheaper transportation alternatives like carpooling or public transit",
    "Create a budget for entertainment expenses and stick to it"
  ];
  
  return (
    <div className="ai-recommendations-card">
      <div className="card-header">
        <span className="icon">💡</span>
        <h2>AI Financial Recommendations</h2>
      </div>
      
      <div className="recommendations-section">
        <h3>Debt Management Suggestions</h3>
        <ul className="recommendations-list">
          {debtRecommendations.map((tip, index) => (
            <li key={index} className="recommendation-item">
              <span className="recommendation-icon">↘️</span>
              <span>{tip}</span>
            </li>
          ))}
        </ul>
      </div>
      
      <div className="recommendations-section">
        <h3>Spending Improvement Tips</h3>
        <ul className="recommendations-list">
          {spendingRecommendations.map((tip, index) => (
            <li key={index} className="recommendation-item">
              <span className="recommendation-icon">📊</span>
              <span>{tip}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default AIRecommendationsCard;